name = "Skyler"
uuid = "804faec8-72f5-11ea-307d-47b816e9b733"
version = "0.1.0"
keywords = ["topological data analysis", "stratified space learning", "point cloud samples", "modelling embeddings"]
license = "MIT"
desc = "Modelling embeddings of stratified spaces from point cloud samples"
author = "Yossi Bokor <yossi.bokor@anu.edu.au>"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Hungarian = "e91730f6-4275-51fb-a7a0-7064cfbd3b39"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
NearestNeighbours = "0a94262d-5824-5211-bd89-2bd2dbcdd6cb"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
SimpleGraphs = "55797a34-41de-5266-9ec1-32ac4eb504d"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1"
CSV = "0.5.16"
SparseArrays = "^1"
Hungarian = "^0"
Eirene = "1"
DataFrames = "0.20.0"
Distances = "0.8.2"
NearestNeighbours = "0.4.4"
PlotlyJS = "0.13.1"
Optim = "0.20.1"
Distributions = "0.22.4"
QuadGK = "2.3.1"
Plots = "0.29.1"
